InstrumentManager:
    BufferSizeForTrades: 10
    BufferSizeForOrderBook: 10

StrategyConfiguration:
    TickerNodeFrequency: 60 # Freq of timer ping
    TickerNodeWaitingSize: 0.1  # TODO: check optimal parameter
