mysql:
    host: localhost
    user: root
    database: DeribitOrderBook
    use_bathes_to_record: False

hdf5:
    hdf5_database_file: "HDF_storage.hdf5"
    use_bathes_to_record: True
    batch_size: 2

orderBookScrapper:
    depth: 10
    test_net: False
    currency: BTC
    enable_traceback: False
    enable_database_record: True
    clean_database: False
    hearth_beat_time: 60
    group_in_limited_order_book: none
    raise_error_at_synthetic: False
    logger_level: INFO

    select_all_order_book: True

    database_daemon: hdf5

    add_extra_instruments: ["BTC-PERPETUAL"]


